SemanticError: line 11: Table(vars): name "a3" not found
