SemanticError: line 3: Table(vars): name "i" not found
